// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/crypto.dart';
import 'api/events.dart';
import 'api/nip17.dart';
import 'api/nip19.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1788978595;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_qiqstr',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  String crateApiEventsCreateBlossomAuthEvent(
      {required String content,
      required String sha256Hash,
      required PlatformInt64 expiration,
      required String privateKeyHex});

  String crateApiEventsCreateCoinosAuthEvent(
      {required String challenge, required String privateKeyHex});

  String crateApiEventsCreateDeletionEvent(
      {required List<String> eventIds,
      required String reason,
      required String privateKeyHex});

  String crateApiEventsCreateFollowEvent(
      {required List<String> followingPubkeys, required String privateKeyHex});

  String crateApiNip17CreateGiftWrapDm(
      {required String senderPrivateKeyHex,
      required String receiverPubkeyHex,
      required String message});

  String crateApiNip17CreateGiftWrapDmForSender(
      {required String senderPrivateKeyHex,
      required String receiverPubkeyHex,
      required String message});

  String crateApiEventsCreateMuteEvent(
      {required List<String> mutedPubkeys, required String privateKeyHex});

  String crateApiEventsCreateNoteEvent(
      {required String content,
      required List<List<String>> tags,
      required String privateKeyHex});

  String crateApiEventsCreateProfileEvent(
      {required String profileJson, required String privateKeyHex});

  String crateApiEventsCreateQuoteEvent(
      {required String content,
      required String quotedEventId,
      String? quotedEventPubkey,
      required String relayUrl,
      required String privateKeyHex,
      required List<List<String>> additionalTags});

  String crateApiEventsCreateReactionEvent(
      {required String targetEventId,
      required String targetAuthor,
      required String content,
      required String privateKeyHex,
      required String relayUrl,
      required int targetKind});

  String crateApiEventsCreateRelayListEvent(
      {required List<String> relayUrls, required String privateKeyHex});

  String crateApiEventsCreateReplyEvent(
      {required String content,
      required List<List<String>> tags,
      required String privateKeyHex});

  String crateApiEventsCreateRepostEvent(
      {required String noteId,
      required String noteAuthor,
      required String content,
      required String privateKeyHex,
      required String relayUrl});

  String crateApiEventsCreateSignedEvent(
      {required int kind,
      required String content,
      required List<List<String>> tags,
      required String privateKeyHex});

  String crateApiEventsCreateZapRequestEvent(
      {required List<List<String>> tags,
      required String content,
      required String privateKeyHex});

  String crateApiNip19EncodeBasicBech32(
      {required String hexStr, required String prefix});

  (String, String) crateApiCryptoGenerateKeypair();

  String crateApiCryptoGenerateMnemonic();

  String crateApiCryptoGetPublicKey({required String privateKeyHex});

  bool crateApiNip17IsGiftWrap({required String eventJson});

  String crateApiCryptoMnemonicToPrivateKey({required String mnemonic});

  String crateApiNip19Nip19Decode({required String bech32Str});

  String crateApiNip19Nip19DecodeTlv({required String bech32Str});

  String crateApiNip19Nip19EncodeNote({required String eventIdHex});

  String crateApiNip19Nip19EncodePrivkey({required String privkeyHex});

  String crateApiNip19Nip19EncodePubkey({required String pubkeyHex});

  String crateApiNip17Nip44Decrypt(
      {required String payload,
      required String receiverSkHex,
      required String senderPkHex});

  String crateApiNip17Nip44Encrypt(
      {required String content,
      required String senderSkHex,
      required String receiverPkHex});

  String crateApiCryptoSignEventId(
      {required String eventIdHex, required String privateKeyHex});

  String crateApiNip17UnwrapGiftWrap(
      {required String receiverPrivateKeyHex, required String giftWrapJson});

  bool crateApiCryptoValidateMnemonic({required String mnemonic});

  bool crateApiCryptoVerifyEvent({required String eventJson});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiEventsCreateBlossomAuthEvent(
      {required String content,
      required String sha256Hash,
      required PlatformInt64 expiration,
      required String privateKeyHex}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(content, serializer);
        sse_encode_String(sha256Hash, serializer);
        sse_encode_i_64(expiration, serializer);
        sse_encode_String(privateKeyHex, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiEventsCreateBlossomAuthEventConstMeta,
      argValues: [content, sha256Hash, expiration, privateKeyHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEventsCreateBlossomAuthEventConstMeta =>
      const TaskConstMeta(
        debugName: "create_blossom_auth_event",
        argNames: ["content", "sha256Hash", "expiration", "privateKeyHex"],
      );

  @override
  String crateApiEventsCreateCoinosAuthEvent(
      {required String challenge, required String privateKeyHex}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(challenge, serializer);
        sse_encode_String(privateKeyHex, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiEventsCreateCoinosAuthEventConstMeta,
      argValues: [challenge, privateKeyHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEventsCreateCoinosAuthEventConstMeta =>
      const TaskConstMeta(
        debugName: "create_coinos_auth_event",
        argNames: ["challenge", "privateKeyHex"],
      );

  @override
  String crateApiEventsCreateDeletionEvent(
      {required List<String> eventIds,
      required String reason,
      required String privateKeyHex}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(eventIds, serializer);
        sse_encode_String(reason, serializer);
        sse_encode_String(privateKeyHex, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiEventsCreateDeletionEventConstMeta,
      argValues: [eventIds, reason, privateKeyHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEventsCreateDeletionEventConstMeta =>
      const TaskConstMeta(
        debugName: "create_deletion_event",
        argNames: ["eventIds", "reason", "privateKeyHex"],
      );

  @override
  String crateApiEventsCreateFollowEvent(
      {required List<String> followingPubkeys, required String privateKeyHex}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(followingPubkeys, serializer);
        sse_encode_String(privateKeyHex, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiEventsCreateFollowEventConstMeta,
      argValues: [followingPubkeys, privateKeyHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEventsCreateFollowEventConstMeta =>
      const TaskConstMeta(
        debugName: "create_follow_event",
        argNames: ["followingPubkeys", "privateKeyHex"],
      );

  @override
  String crateApiNip17CreateGiftWrapDm(
      {required String senderPrivateKeyHex,
      required String receiverPubkeyHex,
      required String message}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(senderPrivateKeyHex, serializer);
        sse_encode_String(receiverPubkeyHex, serializer);
        sse_encode_String(message, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiNip17CreateGiftWrapDmConstMeta,
      argValues: [senderPrivateKeyHex, receiverPubkeyHex, message],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNip17CreateGiftWrapDmConstMeta =>
      const TaskConstMeta(
        debugName: "create_gift_wrap_dm",
        argNames: ["senderPrivateKeyHex", "receiverPubkeyHex", "message"],
      );

  @override
  String crateApiNip17CreateGiftWrapDmForSender(
      {required String senderPrivateKeyHex,
      required String receiverPubkeyHex,
      required String message}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(senderPrivateKeyHex, serializer);
        sse_encode_String(receiverPubkeyHex, serializer);
        sse_encode_String(message, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiNip17CreateGiftWrapDmForSenderConstMeta,
      argValues: [senderPrivateKeyHex, receiverPubkeyHex, message],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNip17CreateGiftWrapDmForSenderConstMeta =>
      const TaskConstMeta(
        debugName: "create_gift_wrap_dm_for_sender",
        argNames: ["senderPrivateKeyHex", "receiverPubkeyHex", "message"],
      );

  @override
  String crateApiEventsCreateMuteEvent(
      {required List<String> mutedPubkeys, required String privateKeyHex}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(mutedPubkeys, serializer);
        sse_encode_String(privateKeyHex, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiEventsCreateMuteEventConstMeta,
      argValues: [mutedPubkeys, privateKeyHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEventsCreateMuteEventConstMeta =>
      const TaskConstMeta(
        debugName: "create_mute_event",
        argNames: ["mutedPubkeys", "privateKeyHex"],
      );

  @override
  String crateApiEventsCreateNoteEvent(
      {required String content,
      required List<List<String>> tags,
      required String privateKeyHex}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(content, serializer);
        sse_encode_list_list_String(tags, serializer);
        sse_encode_String(privateKeyHex, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiEventsCreateNoteEventConstMeta,
      argValues: [content, tags, privateKeyHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEventsCreateNoteEventConstMeta =>
      const TaskConstMeta(
        debugName: "create_note_event",
        argNames: ["content", "tags", "privateKeyHex"],
      );

  @override
  String crateApiEventsCreateProfileEvent(
      {required String profileJson, required String privateKeyHex}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(profileJson, serializer);
        sse_encode_String(privateKeyHex, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiEventsCreateProfileEventConstMeta,
      argValues: [profileJson, privateKeyHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEventsCreateProfileEventConstMeta =>
      const TaskConstMeta(
        debugName: "create_profile_event",
        argNames: ["profileJson", "privateKeyHex"],
      );

  @override
  String crateApiEventsCreateQuoteEvent(
      {required String content,
      required String quotedEventId,
      String? quotedEventPubkey,
      required String relayUrl,
      required String privateKeyHex,
      required List<List<String>> additionalTags}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(content, serializer);
        sse_encode_String(quotedEventId, serializer);
        sse_encode_opt_String(quotedEventPubkey, serializer);
        sse_encode_String(relayUrl, serializer);
        sse_encode_String(privateKeyHex, serializer);
        sse_encode_list_list_String(additionalTags, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiEventsCreateQuoteEventConstMeta,
      argValues: [
        content,
        quotedEventId,
        quotedEventPubkey,
        relayUrl,
        privateKeyHex,
        additionalTags
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEventsCreateQuoteEventConstMeta =>
      const TaskConstMeta(
        debugName: "create_quote_event",
        argNames: [
          "content",
          "quotedEventId",
          "quotedEventPubkey",
          "relayUrl",
          "privateKeyHex",
          "additionalTags"
        ],
      );

  @override
  String crateApiEventsCreateReactionEvent(
      {required String targetEventId,
      required String targetAuthor,
      required String content,
      required String privateKeyHex,
      required String relayUrl,
      required int targetKind}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(targetEventId, serializer);
        sse_encode_String(targetAuthor, serializer);
        sse_encode_String(content, serializer);
        sse_encode_String(privateKeyHex, serializer);
        sse_encode_String(relayUrl, serializer);
        sse_encode_u_16(targetKind, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiEventsCreateReactionEventConstMeta,
      argValues: [
        targetEventId,
        targetAuthor,
        content,
        privateKeyHex,
        relayUrl,
        targetKind
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEventsCreateReactionEventConstMeta =>
      const TaskConstMeta(
        debugName: "create_reaction_event",
        argNames: [
          "targetEventId",
          "targetAuthor",
          "content",
          "privateKeyHex",
          "relayUrl",
          "targetKind"
        ],
      );

  @override
  String crateApiEventsCreateRelayListEvent(
      {required List<String> relayUrls, required String privateKeyHex}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(relayUrls, serializer);
        sse_encode_String(privateKeyHex, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiEventsCreateRelayListEventConstMeta,
      argValues: [relayUrls, privateKeyHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEventsCreateRelayListEventConstMeta =>
      const TaskConstMeta(
        debugName: "create_relay_list_event",
        argNames: ["relayUrls", "privateKeyHex"],
      );

  @override
  String crateApiEventsCreateReplyEvent(
      {required String content,
      required List<List<String>> tags,
      required String privateKeyHex}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(content, serializer);
        sse_encode_list_list_String(tags, serializer);
        sse_encode_String(privateKeyHex, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiEventsCreateReplyEventConstMeta,
      argValues: [content, tags, privateKeyHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEventsCreateReplyEventConstMeta =>
      const TaskConstMeta(
        debugName: "create_reply_event",
        argNames: ["content", "tags", "privateKeyHex"],
      );

  @override
  String crateApiEventsCreateRepostEvent(
      {required String noteId,
      required String noteAuthor,
      required String content,
      required String privateKeyHex,
      required String relayUrl}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(noteId, serializer);
        sse_encode_String(noteAuthor, serializer);
        sse_encode_String(content, serializer);
        sse_encode_String(privateKeyHex, serializer);
        sse_encode_String(relayUrl, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiEventsCreateRepostEventConstMeta,
      argValues: [noteId, noteAuthor, content, privateKeyHex, relayUrl],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEventsCreateRepostEventConstMeta =>
      const TaskConstMeta(
        debugName: "create_repost_event",
        argNames: [
          "noteId",
          "noteAuthor",
          "content",
          "privateKeyHex",
          "relayUrl"
        ],
      );

  @override
  String crateApiEventsCreateSignedEvent(
      {required int kind,
      required String content,
      required List<List<String>> tags,
      required String privateKeyHex}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_16(kind, serializer);
        sse_encode_String(content, serializer);
        sse_encode_list_list_String(tags, serializer);
        sse_encode_String(privateKeyHex, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiEventsCreateSignedEventConstMeta,
      argValues: [kind, content, tags, privateKeyHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEventsCreateSignedEventConstMeta =>
      const TaskConstMeta(
        debugName: "create_signed_event",
        argNames: ["kind", "content", "tags", "privateKeyHex"],
      );

  @override
  String crateApiEventsCreateZapRequestEvent(
      {required List<List<String>> tags,
      required String content,
      required String privateKeyHex}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_list_String(tags, serializer);
        sse_encode_String(content, serializer);
        sse_encode_String(privateKeyHex, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiEventsCreateZapRequestEventConstMeta,
      argValues: [tags, content, privateKeyHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEventsCreateZapRequestEventConstMeta =>
      const TaskConstMeta(
        debugName: "create_zap_request_event",
        argNames: ["tags", "content", "privateKeyHex"],
      );

  @override
  String crateApiNip19EncodeBasicBech32(
      {required String hexStr, required String prefix}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(hexStr, serializer);
        sse_encode_String(prefix, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiNip19EncodeBasicBech32ConstMeta,
      argValues: [hexStr, prefix],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNip19EncodeBasicBech32ConstMeta =>
      const TaskConstMeta(
        debugName: "encode_basic_bech32",
        argNames: ["hexStr", "prefix"],
      );

  @override
  (String, String) crateApiCryptoGenerateKeypair() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_record_string_string,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCryptoGenerateKeypairConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoGenerateKeypairConstMeta =>
      const TaskConstMeta(
        debugName: "generate_keypair",
        argNames: [],
      );

  @override
  String crateApiCryptoGenerateMnemonic() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCryptoGenerateMnemonicConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoGenerateMnemonicConstMeta =>
      const TaskConstMeta(
        debugName: "generate_mnemonic",
        argNames: [],
      );

  @override
  String crateApiCryptoGetPublicKey({required String privateKeyHex}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(privateKeyHex, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCryptoGetPublicKeyConstMeta,
      argValues: [privateKeyHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoGetPublicKeyConstMeta => const TaskConstMeta(
        debugName: "get_public_key",
        argNames: ["privateKeyHex"],
      );

  @override
  bool crateApiNip17IsGiftWrap({required String eventJson}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(eventJson, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiNip17IsGiftWrapConstMeta,
      argValues: [eventJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNip17IsGiftWrapConstMeta => const TaskConstMeta(
        debugName: "is_gift_wrap",
        argNames: ["eventJson"],
      );

  @override
  String crateApiCryptoMnemonicToPrivateKey({required String mnemonic}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(mnemonic, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCryptoMnemonicToPrivateKeyConstMeta,
      argValues: [mnemonic],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoMnemonicToPrivateKeyConstMeta =>
      const TaskConstMeta(
        debugName: "mnemonic_to_private_key",
        argNames: ["mnemonic"],
      );

  @override
  String crateApiNip19Nip19Decode({required String bech32Str}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(bech32Str, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiNip19Nip19DecodeConstMeta,
      argValues: [bech32Str],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNip19Nip19DecodeConstMeta => const TaskConstMeta(
        debugName: "nip19_decode",
        argNames: ["bech32Str"],
      );

  @override
  String crateApiNip19Nip19DecodeTlv({required String bech32Str}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(bech32Str, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiNip19Nip19DecodeTlvConstMeta,
      argValues: [bech32Str],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNip19Nip19DecodeTlvConstMeta =>
      const TaskConstMeta(
        debugName: "nip19_decode_tlv",
        argNames: ["bech32Str"],
      );

  @override
  String crateApiNip19Nip19EncodeNote({required String eventIdHex}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(eventIdHex, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiNip19Nip19EncodeNoteConstMeta,
      argValues: [eventIdHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNip19Nip19EncodeNoteConstMeta =>
      const TaskConstMeta(
        debugName: "nip19_encode_note",
        argNames: ["eventIdHex"],
      );

  @override
  String crateApiNip19Nip19EncodePrivkey({required String privkeyHex}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(privkeyHex, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiNip19Nip19EncodePrivkeyConstMeta,
      argValues: [privkeyHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNip19Nip19EncodePrivkeyConstMeta =>
      const TaskConstMeta(
        debugName: "nip19_encode_privkey",
        argNames: ["privkeyHex"],
      );

  @override
  String crateApiNip19Nip19EncodePubkey({required String pubkeyHex}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(pubkeyHex, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiNip19Nip19EncodePubkeyConstMeta,
      argValues: [pubkeyHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNip19Nip19EncodePubkeyConstMeta =>
      const TaskConstMeta(
        debugName: "nip19_encode_pubkey",
        argNames: ["pubkeyHex"],
      );

  @override
  String crateApiNip17Nip44Decrypt(
      {required String payload,
      required String receiverSkHex,
      required String senderPkHex}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(payload, serializer);
        sse_encode_String(receiverSkHex, serializer);
        sse_encode_String(senderPkHex, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiNip17Nip44DecryptConstMeta,
      argValues: [payload, receiverSkHex, senderPkHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNip17Nip44DecryptConstMeta => const TaskConstMeta(
        debugName: "nip44_decrypt",
        argNames: ["payload", "receiverSkHex", "senderPkHex"],
      );

  @override
  String crateApiNip17Nip44Encrypt(
      {required String content,
      required String senderSkHex,
      required String receiverPkHex}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(content, serializer);
        sse_encode_String(senderSkHex, serializer);
        sse_encode_String(receiverPkHex, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiNip17Nip44EncryptConstMeta,
      argValues: [content, senderSkHex, receiverPkHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNip17Nip44EncryptConstMeta => const TaskConstMeta(
        debugName: "nip44_encrypt",
        argNames: ["content", "senderSkHex", "receiverPkHex"],
      );

  @override
  String crateApiCryptoSignEventId(
      {required String eventIdHex, required String privateKeyHex}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(eventIdHex, serializer);
        sse_encode_String(privateKeyHex, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCryptoSignEventIdConstMeta,
      argValues: [eventIdHex, privateKeyHex],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoSignEventIdConstMeta => const TaskConstMeta(
        debugName: "sign_event_id",
        argNames: ["eventIdHex", "privateKeyHex"],
      );

  @override
  String crateApiNip17UnwrapGiftWrap(
      {required String receiverPrivateKeyHex, required String giftWrapJson}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(receiverPrivateKeyHex, serializer);
        sse_encode_String(giftWrapJson, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiNip17UnwrapGiftWrapConstMeta,
      argValues: [receiverPrivateKeyHex, giftWrapJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNip17UnwrapGiftWrapConstMeta =>
      const TaskConstMeta(
        debugName: "unwrap_gift_wrap",
        argNames: ["receiverPrivateKeyHex", "giftWrapJson"],
      );

  @override
  bool crateApiCryptoValidateMnemonic({required String mnemonic}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(mnemonic, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCryptoValidateMnemonicConstMeta,
      argValues: [mnemonic],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoValidateMnemonicConstMeta =>
      const TaskConstMeta(
        debugName: "validate_mnemonic",
        argNames: ["mnemonic"],
      );

  @override
  bool crateApiCryptoVerifyEvent({required String eventJson}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(eventJson, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 33)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCryptoVerifyEventConstMeta,
      argValues: [eventJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCryptoVerifyEventConstMeta => const TaskConstMeta(
        debugName: "verify_event",
        argNames: ["eventJson"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<List<String>> dco_decode_list_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<List<String>> sse_decode_list_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <List<String>>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (String, String) sse_decode_record_string_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_String(
      List<List<String>> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_record_string_string(
      (String, String) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
