// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_quote`, `melt_with_retry`, `new`, `store`, `wallet_for`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `WalletStore`

/// Receives a Cashu token and melts it to the given Lightning target.
/// Fee-aware: starts with fee offset of 1 sat, increments by 1, max 5 attempts.
///
/// Returns JSON `{ "amount_sats": u64 }`
Future<String> cashuReceiveAndMelt(
        {required String token, required String lightningTarget}) =>
    RustLib.instance.api.crateApiCashuCashuReceiveAndMelt(
        token: token, lightningTarget: lightningTarget);

/// Melts all proofs in the wallet to the given Lightning target.
///
/// Returns JSON `{ "total_sats": u64, "mints": [ { "mint_url": String, "sats": u64 } ] }`
Future<String> cashuMeltAll({required String lightningTarget}) =>
    RustLib.instance.api
        .crateApiCashuCashuMeltAll(lightningTarget: lightningTarget);

/// Decodes a Cashu token: returns mint URL and amount.
///
/// Returns JSON `{ "mint_url": String, "amount_sats": u64 }`
String cashuDecodeToken({required String token}) =>
    RustLib.instance.api.crateApiCashuCashuDecodeToken(token: token);

/// Returns the total Cashu balance across all wallets.
///
/// Returns JSON `{ "total_sats": u64, "mints": [ { "mint_url": String, "sats": u64 } ] }`
Future<String> cashuGetBalance() =>
    RustLib.instance.api.crateApiCashuCashuGetBalance();
