// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

(String, String) generateKeypair() =>
    RustLib.instance.api.crateApiCryptoGenerateKeypair();

String getPublicKey({required String privateKeyHex}) => RustLib.instance.api
    .crateApiCryptoGetPublicKey(privateKeyHex: privateKeyHex);

String signEventId(
        {required String eventIdHex, required String privateKeyHex}) =>
    RustLib.instance.api.crateApiCryptoSignEventId(
        eventIdHex: eventIdHex, privateKeyHex: privateKeyHex);

bool verifyEvent({required String eventJson}) =>
    RustLib.instance.api.crateApiCryptoVerifyEvent(eventJson: eventJson);

String generateMnemonic() =>
    RustLib.instance.api.crateApiCryptoGenerateMnemonic();

bool validateMnemonic({required String mnemonic}) =>
    RustLib.instance.api.crateApiCryptoValidateMnemonic(mnemonic: mnemonic);

String mnemonicToPrivateKey({required String mnemonic}) =>
    RustLib.instance.api.crateApiCryptoMnemonicToPrivateKey(mnemonic: mnemonic);

String generateAesKey() => RustLib.instance.api.crateApiCryptoGenerateAesKey();

String generateAesNonce() =>
    RustLib.instance.api.crateApiCryptoGenerateAesNonce();

String aesGcmEncrypt(
        {required List<int> data,
        required String keyHex,
        required String nonceHex}) =>
    RustLib.instance.api.crateApiCryptoAesGcmEncrypt(
        data: data, keyHex: keyHex, nonceHex: nonceHex);

Uint8List aesGcmDecrypt(
        {required String encryptedBase64,
        required String keyHex,
        required String nonceHex}) =>
    RustLib.instance.api.crateApiCryptoAesGcmDecrypt(
        encryptedBase64: encryptedBase64, keyHex: keyHex, nonceHex: nonceHex);

String sha256Hash({required List<int> data}) =>
    RustLib.instance.api.crateApiCryptoSha256Hash(data: data);
