// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

(String, String) generateKeypair() =>
    RustLib.instance.api.crateApiCryptoGenerateKeypair();

String getPublicKey({required String privateKeyHex}) => RustLib.instance.api
    .crateApiCryptoGetPublicKey(privateKeyHex: privateKeyHex);

String signEventId(
        {required String eventIdHex, required String privateKeyHex}) =>
    RustLib.instance.api.crateApiCryptoSignEventId(
        eventIdHex: eventIdHex, privateKeyHex: privateKeyHex);

bool verifyEvent({required String eventJson}) =>
    RustLib.instance.api.crateApiCryptoVerifyEvent(eventJson: eventJson);

String generateMnemonic() =>
    RustLib.instance.api.crateApiCryptoGenerateMnemonic();

bool validateMnemonic({required String mnemonic}) =>
    RustLib.instance.api.crateApiCryptoValidateMnemonic(mnemonic: mnemonic);

String mnemonicToPrivateKey({required String mnemonic}) =>
    RustLib.instance.api.crateApiCryptoMnemonicToPrivateKey(mnemonic: mnemonic);
