// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `extract_bolt11_amount_sats`, `extract_zap_amount_sats`, `extract_zap_comment`, `extract_zap_sender`, `metadata_to_flat_json`

Future<String?> dbGetProfile({required String pubkeyHex}) =>
    RustLib.instance.api.crateApiDatabaseDbGetProfile(pubkeyHex: pubkeyHex);

Future<String> dbGetProfiles({required List<String> pubkeysHex}) =>
    RustLib.instance.api.crateApiDatabaseDbGetProfiles(pubkeysHex: pubkeysHex);

Future<bool> dbHasProfile({required String pubkeyHex}) =>
    RustLib.instance.api.crateApiDatabaseDbHasProfile(pubkeyHex: pubkeyHex);

Future<String> dbSearchProfiles({required String query, required int limit}) =>
    RustLib.instance.api
        .crateApiDatabaseDbSearchProfiles(query: query, limit: limit);

Future<List<String>> dbGetFollowingList({required String pubkeyHex}) =>
    RustLib.instance.api
        .crateApiDatabaseDbGetFollowingList(pubkeyHex: pubkeyHex);

Future<bool> dbHasFollowingList({required String pubkeyHex}) =>
    RustLib.instance.api
        .crateApiDatabaseDbHasFollowingList(pubkeyHex: pubkeyHex);

Future<List<String>> dbGetMuteList({required String pubkeyHex}) =>
    RustLib.instance.api.crateApiDatabaseDbGetMuteList(pubkeyHex: pubkeyHex);

Future<bool> dbHasMuteList({required String pubkeyHex}) =>
    RustLib.instance.api.crateApiDatabaseDbHasMuteList(pubkeyHex: pubkeyHex);

Future<void> dbSaveFollowingList(
        {required String pubkeyHex, required List<String> followsHex}) =>
    RustLib.instance.api.crateApiDatabaseDbSaveFollowingList(
        pubkeyHex: pubkeyHex, followsHex: followsHex);

Future<void> dbDeleteFollowingList({required String pubkeyHex}) =>
    RustLib.instance.api
        .crateApiDatabaseDbDeleteFollowingList(pubkeyHex: pubkeyHex);

Future<void> dbSaveMuteList(
        {required String pubkeyHex, required List<String> mutedHex}) =>
    RustLib.instance.api.crateApiDatabaseDbSaveMuteList(
        pubkeyHex: pubkeyHex, mutedHex: mutedHex);

Future<void> dbDeleteMuteList({required String pubkeyHex}) =>
    RustLib.instance.api.crateApiDatabaseDbDeleteMuteList(pubkeyHex: pubkeyHex);

Future<String> dbGetFeedNotes(
        {required List<String> authorsHex, required int limit}) =>
    RustLib.instance.api
        .crateApiDatabaseDbGetFeedNotes(authorsHex: authorsHex, limit: limit);

Future<String> dbGetProfileNotes(
        {required String pubkeyHex, required int limit}) =>
    RustLib.instance.api
        .crateApiDatabaseDbGetProfileNotes(pubkeyHex: pubkeyHex, limit: limit);

Future<String> dbGetHashtagNotes(
        {required String hashtag, required int limit}) =>
    RustLib.instance.api
        .crateApiDatabaseDbGetHashtagNotes(hashtag: hashtag, limit: limit);

Future<String?> dbGetEvent({required String eventId}) =>
    RustLib.instance.api.crateApiDatabaseDbGetEvent(eventId: eventId);

Future<bool> dbEventExists({required String eventId}) =>
    RustLib.instance.api.crateApiDatabaseDbEventExists(eventId: eventId);

Future<bool> dbSaveEvent({required String eventJson}) =>
    RustLib.instance.api.crateApiDatabaseDbSaveEvent(eventJson: eventJson);

Future<int> dbSaveEvents({required String eventsJson}) =>
    RustLib.instance.api.crateApiDatabaseDbSaveEvents(eventsJson: eventsJson);

Future<String> dbQueryEvents(
        {required String filterJson, required int limit}) =>
    RustLib.instance.api
        .crateApiDatabaseDbQueryEvents(filterJson: filterJson, limit: limit);

Future<String> dbGetReplies({required String noteId, required int limit}) =>
    RustLib.instance.api
        .crateApiDatabaseDbGetReplies(noteId: noteId, limit: limit);

Future<String> dbGetNotifications(
        {required String userPubkeyHex, required int limit}) =>
    RustLib.instance.api.crateApiDatabaseDbGetNotifications(
        userPubkeyHex: userPubkeyHex, limit: limit);

Future<String> dbGetInteractionCounts({required String noteId}) =>
    RustLib.instance.api.crateApiDatabaseDbGetInteractionCounts(noteId: noteId);

Future<String> dbGetBatchInteractionCounts({required List<String> noteIds}) =>
    RustLib.instance.api
        .crateApiDatabaseDbGetBatchInteractionCounts(noteIds: noteIds);

Future<String> dbGetBatchInteractionData(
        {required List<String> noteIds, required String userPubkeyHex}) =>
    RustLib.instance.api.crateApiDatabaseDbGetBatchInteractionData(
        noteIds: noteIds, userPubkeyHex: userPubkeyHex);

Future<bool> dbHasUserReacted(
        {required String noteId, required String userPubkeyHex}) =>
    RustLib.instance.api.crateApiDatabaseDbHasUserReacted(
        noteId: noteId, userPubkeyHex: userPubkeyHex);

Future<bool> dbHasUserReposted(
        {required String noteId, required String userPubkeyHex}) =>
    RustLib.instance.api.crateApiDatabaseDbHasUserReposted(
        noteId: noteId, userPubkeyHex: userPubkeyHex);

Future<String> dbGetDetailedInteractions({required String noteId}) =>
    RustLib.instance.api
        .crateApiDatabaseDbGetDetailedInteractions(noteId: noteId);

Future<String> dbGetArticles({required int limit}) =>
    RustLib.instance.api.crateApiDatabaseDbGetArticles(limit: limit);

Future<String> dbGetArticlesByAuthors(
        {required List<String> authorsHex, required int limit}) =>
    RustLib.instance.api.crateApiDatabaseDbGetArticlesByAuthors(
        authorsHex: authorsHex, limit: limit);

Future<String?> dbFindUserRepostEventId(
        {required String userPubkeyHex, required String noteId}) =>
    RustLib.instance.api.crateApiDatabaseDbFindUserRepostEventId(
        userPubkeyHex: userPubkeyHex, noteId: noteId);

Future<String> dbGetRandomProfiles({required int limit}) =>
    RustLib.instance.api.crateApiDatabaseDbGetRandomProfiles(limit: limit);

Future<void> dbSaveProfile(
        {required String pubkeyHex, required String profileJson}) =>
    RustLib.instance.api.crateApiDatabaseDbSaveProfile(
        pubkeyHex: pubkeyHex, profileJson: profileJson);

Future<int> dbCountEvents({required String filterJson}) =>
    RustLib.instance.api.crateApiDatabaseDbCountEvents(filterJson: filterJson);

Future<void> dbWipe() => RustLib.instance.api.crateApiDatabaseDbWipe();

Future<String> dbSearchNotes({required String query, required int limit}) =>
    RustLib.instance.api
        .crateApiDatabaseDbSearchNotes(query: query, limit: limit);

Future<String> dbGetOldestEvents({required int limit}) =>
    RustLib.instance.api.crateApiDatabaseDbGetOldestEvents(limit: limit);

Future<int> dbCleanupOldEvents({required int daysToKeep}) =>
    RustLib.instance.api
        .crateApiDatabaseDbCleanupOldEvents(daysToKeep: daysToKeep);

Future<String> dbGetDatabaseStats() =>
    RustLib.instance.api.crateApiDatabaseDbGetDatabaseStats();
