// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `extract_bolt11_amount_sats`, `extract_zap_amount_sats`, `extract_zap_comment`, `extract_zap_sender`, `hydrate_article_events`, `hydrate_notes`, `hydrate_notification_events`, `is_event_muted`, `metadata_to_flat_json`

Future<String?> dbGetProfile({required String pubkeyHex}) =>
    RustLib.instance.api.crateApiDatabaseDbGetProfile(pubkeyHex: pubkeyHex);

Future<String> dbGetProfiles({required List<String> pubkeysHex}) =>
    RustLib.instance.api.crateApiDatabaseDbGetProfiles(pubkeysHex: pubkeysHex);

Future<bool> dbHasProfile({required String pubkeyHex}) =>
    RustLib.instance.api.crateApiDatabaseDbHasProfile(pubkeyHex: pubkeyHex);

Future<String> dbSearchProfiles({required String query, required int limit}) =>
    RustLib.instance.api
        .crateApiDatabaseDbSearchProfiles(query: query, limit: limit);

Future<List<String>> dbGetFollowingList({required String pubkeyHex}) =>
    RustLib.instance.api
        .crateApiDatabaseDbGetFollowingList(pubkeyHex: pubkeyHex);

Future<bool> dbHasFollowingList({required String pubkeyHex}) =>
    RustLib.instance.api
        .crateApiDatabaseDbHasFollowingList(pubkeyHex: pubkeyHex);

Future<List<String>> dbGetMuteList({required String pubkeyHex}) =>
    RustLib.instance.api.crateApiDatabaseDbGetMuteList(pubkeyHex: pubkeyHex);

Future<bool> dbHasMuteList({required String pubkeyHex}) =>
    RustLib.instance.api.crateApiDatabaseDbHasMuteList(pubkeyHex: pubkeyHex);

Future<void> dbSaveFollowingList(
        {required String pubkeyHex, required List<String> followsHex}) =>
    RustLib.instance.api.crateApiDatabaseDbSaveFollowingList(
        pubkeyHex: pubkeyHex, followsHex: followsHex);

Future<void> dbDeleteFollowingList({required String pubkeyHex}) =>
    RustLib.instance.api
        .crateApiDatabaseDbDeleteFollowingList(pubkeyHex: pubkeyHex);

Future<void> dbSaveMuteList(
        {required String pubkeyHex, required List<String> mutedHex}) =>
    RustLib.instance.api.crateApiDatabaseDbSaveMuteList(
        pubkeyHex: pubkeyHex, mutedHex: mutedHex);

Future<void> dbDeleteMuteList({required String pubkeyHex}) =>
    RustLib.instance.api.crateApiDatabaseDbDeleteMuteList(pubkeyHex: pubkeyHex);

Future<String> dbGetFeedNotes(
        {required List<String> authorsHex,
        required int limit,
        required List<String> mutedPubkeys,
        required List<String> mutedWords}) =>
    RustLib.instance.api.crateApiDatabaseDbGetFeedNotes(
        authorsHex: authorsHex,
        limit: limit,
        mutedPubkeys: mutedPubkeys,
        mutedWords: mutedWords);

Future<String> dbGetProfileNotes(
        {required String pubkeyHex,
        required int limit,
        required List<String> mutedPubkeys,
        required List<String> mutedWords}) =>
    RustLib.instance.api.crateApiDatabaseDbGetProfileNotes(
        pubkeyHex: pubkeyHex,
        limit: limit,
        mutedPubkeys: mutedPubkeys,
        mutedWords: mutedWords);

Future<String> dbGetHashtagNotes(
        {required String hashtag,
        required int limit,
        required List<String> mutedPubkeys,
        required List<String> mutedWords}) =>
    RustLib.instance.api.crateApiDatabaseDbGetHashtagNotes(
        hashtag: hashtag,
        limit: limit,
        mutedPubkeys: mutedPubkeys,
        mutedWords: mutedWords);

Future<String?> dbGetEvent({required String eventId}) =>
    RustLib.instance.api.crateApiDatabaseDbGetEvent(eventId: eventId);

Future<bool> dbEventExists({required String eventId}) =>
    RustLib.instance.api.crateApiDatabaseDbEventExists(eventId: eventId);

Future<List<bool>> dbEventsExistBatch({required List<String> eventIds}) =>
    RustLib.instance.api.crateApiDatabaseDbEventsExistBatch(eventIds: eventIds);

Future<bool> dbSaveEvent({required String eventJson}) =>
    RustLib.instance.api.crateApiDatabaseDbSaveEvent(eventJson: eventJson);

Future<int> dbSaveEvents({required String eventsJson}) =>
    RustLib.instance.api.crateApiDatabaseDbSaveEvents(eventsJson: eventsJson);

Future<int> dbDeleteEventsByIds({required List<String> eventIds}) =>
    RustLib.instance.api
        .crateApiDatabaseDbDeleteEventsByIds(eventIds: eventIds);

Future<int> dbProcessDeletionEvents() =>
    RustLib.instance.api.crateApiDatabaseDbProcessDeletionEvents();

Future<String> dbQueryEvents(
        {required String filterJson, required int limit}) =>
    RustLib.instance.api
        .crateApiDatabaseDbQueryEvents(filterJson: filterJson, limit: limit);

Future<String> dbGetReplies(
        {required String noteId,
        required int limit,
        required List<String> mutedPubkeys,
        required List<String> mutedWords}) =>
    RustLib.instance.api.crateApiDatabaseDbGetReplies(
        noteId: noteId,
        limit: limit,
        mutedPubkeys: mutedPubkeys,
        mutedWords: mutedWords);

Future<String> dbGetNotifications(
        {required String userPubkeyHex,
        required int limit,
        required List<String> mutedPubkeys,
        required List<String> mutedWords}) =>
    RustLib.instance.api.crateApiDatabaseDbGetNotifications(
        userPubkeyHex: userPubkeyHex,
        limit: limit,
        mutedPubkeys: mutedPubkeys,
        mutedWords: mutedWords);

Future<String> dbGetInteractionCounts({required String noteId}) =>
    RustLib.instance.api.crateApiDatabaseDbGetInteractionCounts(noteId: noteId);

Future<String> dbGetBatchInteractionCounts({required List<String> noteIds}) =>
    RustLib.instance.api
        .crateApiDatabaseDbGetBatchInteractionCounts(noteIds: noteIds);

Future<String> dbGetBatchInteractionData(
        {required List<String> noteIds, required String userPubkeyHex}) =>
    RustLib.instance.api.crateApiDatabaseDbGetBatchInteractionData(
        noteIds: noteIds, userPubkeyHex: userPubkeyHex);

Future<bool> dbHasUserReacted(
        {required String noteId, required String userPubkeyHex}) =>
    RustLib.instance.api.crateApiDatabaseDbHasUserReacted(
        noteId: noteId, userPubkeyHex: userPubkeyHex);

Future<bool> dbHasUserReposted(
        {required String noteId, required String userPubkeyHex}) =>
    RustLib.instance.api.crateApiDatabaseDbHasUserReposted(
        noteId: noteId, userPubkeyHex: userPubkeyHex);

Future<String> dbGetDetailedInteractions({required String noteId}) =>
    RustLib.instance.api
        .crateApiDatabaseDbGetDetailedInteractions(noteId: noteId);

Future<String> dbGetArticles(
        {required int limit,
        required List<String> mutedPubkeys,
        required List<String> mutedWords}) =>
    RustLib.instance.api.crateApiDatabaseDbGetArticles(
        limit: limit, mutedPubkeys: mutedPubkeys, mutedWords: mutedWords);

Future<String> dbGetArticlesByAuthors(
        {required List<String> authorsHex,
        required int limit,
        required List<String> mutedPubkeys,
        required List<String> mutedWords}) =>
    RustLib.instance.api.crateApiDatabaseDbGetArticlesByAuthors(
        authorsHex: authorsHex,
        limit: limit,
        mutedPubkeys: mutedPubkeys,
        mutedWords: mutedWords);

Future<String?> dbFindUserRepostEventId(
        {required String userPubkeyHex, required String noteId}) =>
    RustLib.instance.api.crateApiDatabaseDbFindUserRepostEventId(
        userPubkeyHex: userPubkeyHex, noteId: noteId);

Future<String> dbGetRandomProfiles({required int limit}) =>
    RustLib.instance.api.crateApiDatabaseDbGetRandomProfiles(limit: limit);

Future<void> dbSaveProfile(
        {required String pubkeyHex, required String profileJson}) =>
    RustLib.instance.api.crateApiDatabaseDbSaveProfile(
        pubkeyHex: pubkeyHex, profileJson: profileJson);

Future<int> dbCountEvents({required String filterJson}) =>
    RustLib.instance.api.crateApiDatabaseDbCountEvents(filterJson: filterJson);

Future<void> dbWipe() => RustLib.instance.api.crateApiDatabaseDbWipe();

Future<void> dbWipeDirectory() =>
    RustLib.instance.api.crateApiDatabaseDbWipeDirectory();

Future<String> dbSearchNotes({required String query, required int limit}) =>
    RustLib.instance.api
        .crateApiDatabaseDbSearchNotes(query: query, limit: limit);

Future<String> dbGetOldestEvents({required int limit}) =>
    RustLib.instance.api.crateApiDatabaseDbGetOldestEvents(limit: limit);

Future<int> dbCleanupOldEvents({required int daysToKeep}) =>
    RustLib.instance.api
        .crateApiDatabaseDbCleanupOldEvents(daysToKeep: daysToKeep);

Future<int> dbCleanupByKind({required int kindNum, required int daysToKeep}) =>
    RustLib.instance.api.crateApiDatabaseDbCleanupByKind(
        kindNum: kindNum, daysToKeep: daysToKeep);

Future<int> dbCleanupForeignContactLists({required String ownPubkeyHex}) =>
    RustLib.instance.api.crateApiDatabaseDbCleanupForeignContactLists(
        ownPubkeyHex: ownPubkeyHex);

Future<String> dbSmartCleanup(
        {required String ownPubkeyHex,
        required int interactionDays,
        required int noteDays}) =>
    RustLib.instance.api.crateApiDatabaseDbSmartCleanup(
        ownPubkeyHex: ownPubkeyHex,
        interactionDays: interactionDays,
        noteDays: noteDays);

Future<String> dbGetDatabaseStats() =>
    RustLib.instance.api.crateApiDatabaseDbGetDatabaseStats();

Future<String> dbGetHydratedFeedNotes(
        {required List<String> authorsHex,
        required int limit,
        required List<String> mutedPubkeys,
        required List<String> mutedWords,
        required bool filterReplies,
        String? currentUserPubkeyHex}) =>
    RustLib.instance.api.crateApiDatabaseDbGetHydratedFeedNotes(
        authorsHex: authorsHex,
        limit: limit,
        mutedPubkeys: mutedPubkeys,
        mutedWords: mutedWords,
        filterReplies: filterReplies,
        currentUserPubkeyHex: currentUserPubkeyHex);

Future<String> dbGetHydratedProfileNotes(
        {required String pubkeyHex,
        required int limit,
        required List<String> mutedPubkeys,
        required List<String> mutedWords,
        required bool filterReplies,
        String? currentUserPubkeyHex}) =>
    RustLib.instance.api.crateApiDatabaseDbGetHydratedProfileNotes(
        pubkeyHex: pubkeyHex,
        limit: limit,
        mutedPubkeys: mutedPubkeys,
        mutedWords: mutedWords,
        filterReplies: filterReplies,
        currentUserPubkeyHex: currentUserPubkeyHex);

Future<String> dbGetHydratedHashtagNotes(
        {required String hashtag,
        required int limit,
        required List<String> mutedPubkeys,
        required List<String> mutedWords,
        String? currentUserPubkeyHex}) =>
    RustLib.instance.api.crateApiDatabaseDbGetHydratedHashtagNotes(
        hashtag: hashtag,
        limit: limit,
        mutedPubkeys: mutedPubkeys,
        mutedWords: mutedWords,
        currentUserPubkeyHex: currentUserPubkeyHex);

Future<String> dbGetHydratedReplies(
        {required String noteId,
        required int limit,
        required List<String> mutedPubkeys,
        required List<String> mutedWords,
        String? currentUserPubkeyHex}) =>
    RustLib.instance.api.crateApiDatabaseDbGetHydratedReplies(
        noteId: noteId,
        limit: limit,
        mutedPubkeys: mutedPubkeys,
        mutedWords: mutedWords,
        currentUserPubkeyHex: currentUserPubkeyHex);

Future<String?> dbGetHydratedNote(
        {required String eventId, String? currentUserPubkeyHex}) =>
    RustLib.instance.api.crateApiDatabaseDbGetHydratedNote(
        eventId: eventId, currentUserPubkeyHex: currentUserPubkeyHex);

Future<String> dbGetHydratedNotifications(
        {required String userPubkeyHex,
        required int limit,
        required List<String> mutedPubkeys,
        required List<String> mutedWords}) =>
    RustLib.instance.api.crateApiDatabaseDbGetHydratedNotifications(
        userPubkeyHex: userPubkeyHex,
        limit: limit,
        mutedPubkeys: mutedPubkeys,
        mutedWords: mutedWords);

Future<String> dbGetHydratedArticles(
        {required int limit,
        required List<String> mutedPubkeys,
        required List<String> mutedWords}) =>
    RustLib.instance.api.crateApiDatabaseDbGetHydratedArticles(
        limit: limit, mutedPubkeys: mutedPubkeys, mutedWords: mutedWords);

Future<String> dbGetHydratedArticlesByAuthors(
        {required List<String> authorsHex,
        required int limit,
        required List<String> mutedPubkeys,
        required List<String> mutedWords}) =>
    RustLib.instance.api.crateApiDatabaseDbGetHydratedArticlesByAuthors(
        authorsHex: authorsHex,
        limit: limit,
        mutedPubkeys: mutedPubkeys,
        mutedWords: mutedWords);

Future<String?> dbGetHydratedArticle({required String eventId}) =>
    RustLib.instance.api.crateApiDatabaseDbGetHydratedArticle(eventId: eventId);
