// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String createSignedEvent(
        {required int kind,
        required String content,
        required List<List<String>> tags,
        required String privateKeyHex}) =>
    RustLib.instance.api.crateApiEventsCreateSignedEvent(
        kind: kind, content: content, tags: tags, privateKeyHex: privateKeyHex);

String createNoteEvent(
        {required String content,
        required List<List<String>> tags,
        required String privateKeyHex}) =>
    RustLib.instance.api.crateApiEventsCreateNoteEvent(
        content: content, tags: tags, privateKeyHex: privateKeyHex);

String createReactionEvent(
        {required String targetEventId,
        required String targetAuthor,
        required String content,
        required String privateKeyHex,
        required String relayUrl,
        required int targetKind}) =>
    RustLib.instance.api.crateApiEventsCreateReactionEvent(
        targetEventId: targetEventId,
        targetAuthor: targetAuthor,
        content: content,
        privateKeyHex: privateKeyHex,
        relayUrl: relayUrl,
        targetKind: targetKind);

String createReplyEvent(
        {required String content,
        required List<List<String>> tags,
        required String privateKeyHex}) =>
    RustLib.instance.api.crateApiEventsCreateReplyEvent(
        content: content, tags: tags, privateKeyHex: privateKeyHex);

String createRepostEvent(
        {required String noteId,
        required String noteAuthor,
        required String content,
        required String privateKeyHex,
        required String relayUrl}) =>
    RustLib.instance.api.crateApiEventsCreateRepostEvent(
        noteId: noteId,
        noteAuthor: noteAuthor,
        content: content,
        privateKeyHex: privateKeyHex,
        relayUrl: relayUrl);

String createDeletionEvent(
        {required List<String> eventIds,
        required String reason,
        required String privateKeyHex}) =>
    RustLib.instance.api.crateApiEventsCreateDeletionEvent(
        eventIds: eventIds, reason: reason, privateKeyHex: privateKeyHex);

String createProfileEvent(
        {required String profileJson, required String privateKeyHex}) =>
    RustLib.instance.api.crateApiEventsCreateProfileEvent(
        profileJson: profileJson, privateKeyHex: privateKeyHex);

String createFollowEvent(
        {required List<String> followingPubkeys,
        required String privateKeyHex}) =>
    RustLib.instance.api.crateApiEventsCreateFollowEvent(
        followingPubkeys: followingPubkeys, privateKeyHex: privateKeyHex);

String createMuteEvent(
        {required List<String> mutedPubkeys, required String privateKeyHex}) =>
    RustLib.instance.api.crateApiEventsCreateMuteEvent(
        mutedPubkeys: mutedPubkeys, privateKeyHex: privateKeyHex);

String createZapRequestEvent(
        {required List<List<String>> tags,
        required String content,
        required String privateKeyHex}) =>
    RustLib.instance.api.crateApiEventsCreateZapRequestEvent(
        tags: tags, content: content, privateKeyHex: privateKeyHex);

String createQuoteEvent(
        {required String content,
        required String quotedEventId,
        String? quotedEventPubkey,
        required String relayUrl,
        required String privateKeyHex,
        required List<List<String>> additionalTags}) =>
    RustLib.instance.api.crateApiEventsCreateQuoteEvent(
        content: content,
        quotedEventId: quotedEventId,
        quotedEventPubkey: quotedEventPubkey,
        relayUrl: relayUrl,
        privateKeyHex: privateKeyHex,
        additionalTags: additionalTags);

String createBlossomAuthEvent(
        {required String content,
        required String sha256Hash,
        required PlatformInt64 expiration,
        required String privateKeyHex}) =>
    RustLib.instance.api.crateApiEventsCreateBlossomAuthEvent(
        content: content,
        sha256Hash: sha256Hash,
        expiration: expiration,
        privateKeyHex: privateKeyHex);

String createRelayListEvent(
        {required List<String> relayUrls, required String privateKeyHex}) =>
    RustLib.instance.api.crateApiEventsCreateRelayListEvent(
        relayUrls: relayUrls, privateKeyHex: privateKeyHex);

String createRelayListEventWithMarkers(
        {required List<String> relayConfigs, required String privateKeyHex}) =>
    RustLib.instance.api.crateApiEventsCreateRelayListEventWithMarkers(
        relayConfigs: relayConfigs, privateKeyHex: privateKeyHex);

String createCoinosAuthEvent(
        {required String challenge, required String privateKeyHex}) =>
    RustLib.instance.api.crateApiEventsCreateCoinosAuthEvent(
        challenge: challenge, privateKeyHex: privateKeyHex);
