// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cache_dir`, `cached_path`, `ext_from_url`, `semaphore`, `touch_meta`, `url_to_filename`

Future<void> initImageCache({required String cacheDir}) =>
    RustLib.instance.api.crateApiImageCacheInitImageCache(cacheDir: cacheDir);

Future<String?> getCachedImagePath({required String url}) =>
    RustLib.instance.api.crateApiImageCacheGetCachedImagePath(url: url);

Future<String> fetchAndCacheImage({required String url}) =>
    RustLib.instance.api.crateApiImageCacheFetchAndCacheImage(url: url);

Future<void> prefetchImages({required List<String> urls}) =>
    RustLib.instance.api.crateApiImageCachePrefetchImages(urls: urls);

Future<bool> isVideoUrl({required String url}) =>
    RustLib.instance.api.crateApiImageCacheIsVideoUrl(url: url);

Future<bool> isCached({required String url}) =>
    RustLib.instance.api.crateApiImageCacheIsCached(url: url);

Future<void> prefetchNoteImages({required List<String> urls}) =>
    RustLib.instance.api.crateApiImageCachePrefetchNoteImages(urls: urls);

Future<int> evictImageCache({required BigInt maxAgeSecs}) =>
    RustLib.instance.api
        .crateApiImageCacheEvictImageCache(maxAgeSecs: maxAgeSecs);

Future<double> getImageCacheSizeMb() =>
    RustLib.instance.api.crateApiImageCacheGetImageCacheSizeMb();
