// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String nip19Decode({required String bech32Str}) =>
    RustLib.instance.api.crateApiNip19Nip19Decode(bech32Str: bech32Str);

String nip19DecodeTlv({required String bech32Str}) =>
    RustLib.instance.api.crateApiNip19Nip19DecodeTlv(bech32Str: bech32Str);

String nip19EncodePubkey({required String pubkeyHex}) =>
    RustLib.instance.api.crateApiNip19Nip19EncodePubkey(pubkeyHex: pubkeyHex);

String nip19EncodePrivkey({required String privkeyHex}) => RustLib.instance.api
    .crateApiNip19Nip19EncodePrivkey(privkeyHex: privkeyHex);

String nip19EncodeNote({required String eventIdHex}) =>
    RustLib.instance.api.crateApiNip19Nip19EncodeNote(eventIdHex: eventIdHex);

String encodeBasicBech32({required String hexStr, required String prefix}) =>
    RustLib.instance.api
        .crateApiNip19EncodeBasicBech32(hexStr: hexStr, prefix: prefix);
