// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';



String createGiftWrapDm(
        {required String senderPrivateKeyHex,
        required String receiverPubkeyHex,
        required String message}) =>
    RustLib.instance.api.crateApiNip17CreateGiftWrapDm(
        senderPrivateKeyHex: senderPrivateKeyHex,
        receiverPubkeyHex: receiverPubkeyHex,
        message: message);



String createGiftWrapDmForSender(
        {required String senderPrivateKeyHex,
        required String receiverPubkeyHex,
        required String message}) =>
    RustLib.instance.api.crateApiNip17CreateGiftWrapDmForSender(
        senderPrivateKeyHex: senderPrivateKeyHex,
        receiverPubkeyHex: receiverPubkeyHex,
        message: message);













String createGiftWrapFileMessage(
        {required String senderPrivateKeyHex,
        required String receiverPubkeyHex,
        required String fileUrl,
        required String mimeType,
        required String encryptionKeyHex,
        required String encryptionNonceHex,
        required String encryptedHash,
        required String originalHash,
        BigInt? fileSize}) =>
    RustLib.instance.api.crateApiNip17CreateGiftWrapFileMessage(
        senderPrivateKeyHex: senderPrivateKeyHex,
        receiverPubkeyHex: receiverPubkeyHex,
        fileUrl: fileUrl,
        mimeType: mimeType,
        encryptionKeyHex: encryptionKeyHex,
        encryptionNonceHex: encryptionNonceHex,
        encryptedHash: encryptedHash,
        originalHash: originalHash,
        fileSize: fileSize);



String createGiftWrapFileMessageForSender(
        {required String senderPrivateKeyHex,
        required String receiverPubkeyHex,
        required String fileUrl,
        required String mimeType,
        required String encryptionKeyHex,
        required String encryptionNonceHex,
        required String encryptedHash,
        required String originalHash,
        BigInt? fileSize}) =>
    RustLib.instance.api.crateApiNip17CreateGiftWrapFileMessageForSender(
        senderPrivateKeyHex: senderPrivateKeyHex,
        receiverPubkeyHex: receiverPubkeyHex,
        fileUrl: fileUrl,
        mimeType: mimeType,
        encryptionKeyHex: encryptionKeyHex,
        encryptionNonceHex: encryptionNonceHex,
        encryptedHash: encryptedHash,
        originalHash: originalHash,
        fileSize: fileSize);





String unwrapGiftWrap(
        {required String receiverPrivateKeyHex,
        required String giftWrapJson}) =>
    RustLib.instance.api.crateApiNip17UnwrapGiftWrap(
        receiverPrivateKeyHex: receiverPrivateKeyHex,
        giftWrapJson: giftWrapJson);


bool isGiftWrap({required String eventJson}) =>
    RustLib.instance.api.crateApiNip17IsGiftWrap(eventJson: eventJson);



String nip44Encrypt(
        {required String content,
        required String senderSkHex,
        required String receiverPkHex}) =>
    RustLib.instance.api.crateApiNip17Nip44Encrypt(
        content: content,
        senderSkHex: senderSkHex,
        receiverPkHex: receiverPkHex);



String nip44Decrypt(
        {required String payload,
        required String receiverSkHex,
        required String senderPkHex}) =>
    RustLib.instance.api.crateApiNip17Nip44Decrypt(
        payload: payload,
        receiverSkHex: receiverSkHex,
        senderPkHex: senderPkHex);
