// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

bool validateNwcUri({required String uri}) =>
    RustLib.instance.api.crateApiNwcValidateNwcUri(uri: uri);

String parseNwcUri({required String uri}) =>
    RustLib.instance.api.crateApiNwcParseNwcUri(uri: uri);

Future<String> nwcPayInvoice(
        {required String nwcUri, required String invoice}) =>
    RustLib.instance.api
        .crateApiNwcNwcPayInvoice(nwcUri: nwcUri, invoice: invoice);

Future<String> nwcGetBalance({required String nwcUri}) =>
    RustLib.instance.api.crateApiNwcNwcGetBalance(nwcUri: nwcUri);

Future<String> nwcMakeInvoice(
        {required String nwcUri,
        required BigInt amountMsats,
        String? description}) =>
    RustLib.instance.api.crateApiNwcNwcMakeInvoice(
        nwcUri: nwcUri, amountMsats: amountMsats, description: description);

Future<String> nwcListTransactions(
        {required String nwcUri, BigInt? limit, BigInt? offset}) =>
    RustLib.instance.api.crateApiNwcNwcListTransactions(
        nwcUri: nwcUri, limit: limit, offset: offset);
